### ISSUE TITLE
why does is take erekir resources to launch to the other sector

### ISSUE THREAD

**Issue by k3vin0210** [FredyJabe/aeyama#112]
**Mod Build:** *0.2*

---

**Issue:** *it takes the the base games resources*

---
![Screenshot 2023-06-05 6 42 09 PM](https://github.com/FredyJabe/aeyama/assets/135668916/e5a52252-a885-4fdd-8c66-7ff900651153)

**Screenshots:** *If you have something to show.*

**Comment by RGBProductions** [comment]
Incomplete sector.

**Comment by k3vin0210** [comment]
ohh ok

**Comment by k3vin0210** [comment]
that makes sense

**Comment by k3vin0210** [comment]
the first sector is sill realy fun
thanks for helping make the mod

**Comment by SunkyMP3G** [comment]
These are **_Serpulo_** items

**Comment by RGBProductions** [comment]
> the first sector is sill realy fun thanks for helping make the mod

i changed the atmosphere color and added 1 sprite, idk if that really counts for anything LOL

**Comment by SunkyMP3G** [comment]
Close this issue

**Comment by k3vin0210** [comment]
Ohh ok

**Comment by k3vin0210** [comment]
nice update :D

**Comment by k3vin0210** [comment]
should probably wait for the patch tho
