### ISSUE TITLE
quest line bug

### ISSUE THREAD

**Issue by k3vin0210** [FredyJabe/aeyama#122]
**Mod Build:** *151*
**Game Build:** *144.3*

---*most likely a update bug*

**Issue:** *quest line bug*

**Steps to Reproduce:*open a campain save*

---

**Screenshots:** *If you have something to show.*
<img width="960" alt="Capture PNG2" src="https://github.com/FredyJabe/aeyama/assets/135668916/fa221a7a-904a-40a5-aa1f-1401772ea6fb">

**Comment by SunkyMP3G** [comment]
Copper is bug, but I think 10k is intended

**Comment by JojoFR1** [comment]
Intended for testing (god I forgot to update the first sector and make it playable)

**Comment by k3vin0210** [comment]
Nice update any way
