### ISSUE TITLE
2nd sector launch requirements

### ISSUE THREAD

**Issue by JojoFR1** [FredyJabe/aeyama#125]
**Mod Build:** 158dev
**Game Build:** v144.3

---

**Issue:** The 2nd sector still ask for Vanilla Copper and Lead, even tho the core is the modded one and there's a schematics for it in the files.

**Steps to Reproduce:**
1. Go to Aeyama Planet.
   1. Unlock the 2nd sector if not already.
2. Try to launch to the 2nd sector.

---

**Screenshots:** None

**Comment by k3vin0210** [comment]
also when you get there it spawns a base game core

**Comment by JojoFR1** [comment]
> also when you get there it spawns a base game core

Really, are you sure it's a `Core: Shard` (Vanilla) and not a `Core: Frontline Outpost` (From the mod)?

**Comment by k3vin0210** [comment]
they both spawn

**Comment by JojoFR1** [comment]
Oh yeah duro the launch animation, yeah I know. I will look at that later on how to fix

**Comment by k3vin0210** [comment]
ok and the item bug is fixed

**Comment by k3vin0210** [comment]
someone else did it
