### ISSUE TITLE
Core drop pod to outpost

### ISSUE THREAD

**Issue by Jakoblillie** [FredyJabe/aeyama#70]
On new world it says to build a 2x2 core frontline outpost on top of the existing 1x1 core drop pod but it won't allow me to build

**Comment by FredyJabe** [comment]
The drop pod needs to be at the bottom-left of the new core.

**Comment by JojoFR1** [comment]
The 1x1 core need to be in the bottom left corner of the 2x2 core, like this:

![image](https://user-images.githubusercontent.com/110781915/226362456-1a94bb05-759e-4e50-be9d-9b7ca8ed8428.png)

**Comment by JojoFR1** [comment]
If you need further help, you can come to the ![Discord](https://discord.com/invite/rNhkswkJst)!

**Comment by Jakoblillie** [comment]
![Screenshot_20230320_105725_Mindustry](https://user-images.githubusercontent.com/128391306/226379657-1adda465-9fc3-468a-b98f-90ee54d9db30.jpg)
It still won't allow me to place it

**Comment by Hamkiri** [comment]
The resource limit is too low Can't build an outpost

**Comment by SunkyMP3G** [comment]
Build stockpiles
