### ISSUE TITLE
Crawler & Swarmer outlines are looking strange

### ISSUE THREAD

**Issue by SunkyMP3G** [FredyJabe/aeyama#76]
Just ignore that bug with block, I was having fun with code
![image](https://user-images.githubusercontent.com/125795960/228223494-c2c1d401-0905-4e7c-9b42-f95b15f34276.png)

**Comment by JojoFR1** [comment]
It's just the texture (if I'm right), it's @FredyJabe who did it and he's not really an artist

**Comment by SunkyMP3G** [comment]
I think there's a way how to recolor/remove outline, and crawlers need a legs' joint (...crawler-**joint**)
