### ISSUE TITLE
Crash when loading 'New World'

### ISSUE THREAD

**Issue by EXPerience255** [FredyJabe/aeyama#8]
![Screenshot 2023-01-11 053354](https://user-images.githubusercontent.com/71566449/211796088-7ae4185b-c0c5-46e9-b5e2-421a666a4f80.png)
As shown in the error, when I try to open the sector, it crashes due to the lack of a core (according to the crash). Is there a core on it?

**Comment by JojoFR1** [comment]
The mod on the mod browser is actually old, but it's currently fixed

**Comment by EXPerience255** [comment]
Oh, ok. Thanks!
