### ISSUE TITLE
Missing unit sprites

### ISSUE THREAD

**Issue by SunkyMP3G** [FredyJabe/aeyama#87]
On this image you can see all missing sprites of every core unit ~~(crawler and swarmer are fine)~~
![image](https://user-images.githubusercontent.com/125795960/233670179-61022a81-e20c-449e-b2d8-5d617a974ebf.png)

**Comment by FredyJabe** [comment]
Thanks for the report, I'm on it.
Will be fixed tomorrow.

**Comment by SunkyMP3G** [comment]
@FredyJabe I found the problem with main sprites, the line `drawBody: false` was deleting the main sprite of units. I fixed all sprites except cells, because I don't know how to make good sprites for your units, the pull request soon will be ready
